### ISSUE TITLE
Post function in UserQueryDeviceParticipants

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#57]
The following lines (148-149) 
`            if device_part:
                json_device_part['id_device_participant'] = device_part.id_device_site`

The bug arise when the line 149 is called, the error is the following :
2020-10-09 10:56:18-0400 [-] AttributeError: 'TeraDeviceParticipant' object has no attribute 'id_device_site'

**Comment by doumdi** [comment]
Fixed to json_device_part['id_device_participant'] = device_part.id_device_participant
