### ISSUE TITLE
Post function in UserQueryDeviceProject

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#58]
The post function can't update the id_device_project of an already existing one as it takes the already existing ID for the 'new' output : 
`json_device_projects = request.json['device_project']       # gets the project
        if not isinstance(json_device_projects, list):
            json_device_projects = [json_device_projects]

        # Validate if we have an id
        for json_device_project in json_device_projects:
            if 'id_device' not in json_device_project or 'id_project' not in json_device_project:
                return gettext('Missing fields in body'), 400

            # Check if current user can modify the posted device
            if json_device_project['id_project'] not in user_access.get_accessible_projects_ids(admin_only=True) or\
                    json_device_project['id_device'] not in user_access.get_accessible_devices_ids(admin_only=True):
                return gettext('Forbidden'), 403

            # Check if already exists
            device_project = TeraDeviceProject.get_device_project_id_for_device_and_project(
                device_id=json_device_project['id_device'], project_id=json_device_project['id_project'])

            if device_project:
                json_device_project['id_device_project'] = device_project.id_device_project **# remplace the id_device_project in the json by the already existing one**
            else:
                json_device_project['id_device_project'] = 0

            # Do the update!
            if json_device_project['id_device_project'] > 0:
                # Already existing
                try:
                    TeraDeviceProject.update(json_device_project['id_device_project'], json_device_project)`

**Comment by doumdi** [comment]
Please add more details on what the post contains and what is the problematic behavior.

**Comment by arsp2701** [comment]
For instance, there is a link between the id_device : 1 and the id_project : 1. This link has the id_device_project : 1 as we can see in PgAdmin : 
![image](https://user-images.githubusercontent.com/47791043/96172673-bf58a980-0ef4-11eb-8888-9dfbd7f162d7.png)
When we try to update the existing id_project_device, the post function can't and send back the previous link with the previous ID. If tried in localhost : 
![image](https://user-images.githubusercontent.com/47791043/96172823-f464fc00-0ef4-11eb-853b-6ff52fdb33af.png)
We can see that the response body consist of :
`[
  {
    "id_device": 1,
    "id_device_project": 1,
    "id_project": 1
  }
]`
when an update to 
`{
    "id_device": 1,
    "id_device_project": 23,
    "id_project": 1
  }`
is asked. 
My question is, is it a intended behaviour?

**Comment by SBriere** [comment]
Yes, in this case, this is the correct behavior.
This is done to prevent a device being associated many times to the same project. 
If the id_device / id_project association already exists, it is simply updated / returned, thus overwriting the id_device_project with the value in the database. For that API, the id_device_project is optional, and is ignored in the underlying code.
