### ISSUE TITLE
Adding id_device_type in UserQueryDevices

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#59]
When looking at the file UserQueryDevices.py, there is the get function with an id_device_subtype but not id_device_type. I could be added since there is an id_device_type present since the Ref#56 merge.

The following work could be done: 
- Adding Parser in get function with id_device_type
- In the get func, adding the following in the decision tree :
`            if args['id_device_type']:
                devices = user_access.query_devices_by_type(args['id_device_type'])`
- Add an id_device_type in the post function

**Comment by doumdi** [comment]
Seems fixed in the dev branch, can you verify.

**Comment by arsp2701** [comment]
Present on newest version confirmed!
