### ISSUE TITLE
Get function UserQueryDevice / DBManagerTeraUserAccess

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#61]
The Get func in UserQueryDevice is subject of a bug caused in DBManagerTeraUserAccess : 
when calling a valid ''id_site'' or ''id_project'' argument (i.e. ''1'') we can recieve the following info *(all the flags are None, except ''list'' which is true to limit the information) : 
![image](https://user-images.githubusercontent.com/47791043/96271149-870ba680-0f9a-11eb-9a5e-a7c8a5cbf309.png)
The bug arises when the  ''enable'' flag is set to false, giving the following info : 
![image](https://user-images.githubusercontent.com/47791043/96271277-aefb0a00-0f9a-11eb-8d81-c4b4a043536c.png)

I suspect the bug is caused by the DBManagerTeraUserAccess query_devices_for_site method : 
def query_devices_for_site(self, site_id: int, device_type_id: int, enabled: bool = False):
        devices = []
        if site_id in self.get_accessible_sites_ids():
            query = TeraDevice.query.join(TeraDeviceProject).join(TeraProject) \
                .filter(TeraProject.id_site == site_id) \
                .order_by(TeraDevice.id_device.asc())
            if device_type_id:
                query = query.filter(TeraDevice.id_device_type == device_type_id)
            if enabled is not None:
                query = query.filter(TeraDevice.device_enabled == enabled)
            devices = query.all()
        return devices
The portion ` if enabled is not None:` is true when the flag is false hence continuing with 
`query = query.filter(TeraDevice.device_enabled == enabled)` but because enable != false, a empty list is returned.

The proposed fix is to change the if statement from ` if enabled is not None:` to `if enable`

This fix is applicable to query_devices_for_site and query_devices_for_project functions.

**Comment by doumdi** [comment]
OK! Please fix and create a pull request.
