### ISSUE TITLE
Get function UserQueryDevices 

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#62]
When the list flag is True the get function returns only ids : 
![image](https://user-images.githubusercontent.com/47791043/96291466-0eb2de80-0fb6-11eb-97a5-ac878a41d0ba.png)
Should the id_device_type be included in the list ? (i.e. remove the id_device_type in the ignore fields in TeraDevice in line 56) since the id_device_subtype is present? 
![image](https://user-images.githubusercontent.com/47791043/96291585-40c44080-0fb6-11eb-8f4e-ac22b7f13bba.png)

**Comment by doumdi** [comment]
@arsp2701 , yes remove id_device_type from ignore_fields.
