### ISSUE TITLE
Post Function UserQueryDeviceParticipant - can't update the id_device_participant

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#63]
The post function of UserQueryDeviceParticipant cannot update the id_device_participant if the link already existed.
Ex : the link of id_device :1 and id_participant :1 is id_device_participant :1. If we try to update the id_device_participant with the post function (in this example, I tried to modify the id_device_participant to 8) : 
![image](https://user-images.githubusercontent.com/47791043/96464352-b407c580-11f5-11eb-94cb-ffee082464df.png)

Is this an expected behaviour?

**Comment by SBriere** [comment]
Same logic and reasoning behind that API as Refs #58, but applied to device participants instead.
