### ISSUE TITLE
Get function UserQueryDeviceParticipant - 

### ISSUE THREAD

**Issue by arsp2701** [introlab/opentera#69]
It is mentioned in the help of the get function of UserQueryDeviceParticipant (UQDPar) that only one ID is supported at once. When only an id_device_type is entered, the server answer with an empty list. It is because the id_device_type is a filter for the id_participant in the code (UQDPar.py):
`        elif args['id_participant']:`
            `if args['id_participant'] in user_access.get_accessible_participants_ids():`
                `if args['id_device_type']:`
                   ` device_part = user_access.query_device_participants_by_type(id_device_type=args['id_device_type'],participant_id=args['id_participant'])`
               ` else:`
                   ` device_part = TeraDeviceParticipant.query_devices_for_participant(
                        participant_id=args['id_participant'])`

Should we change the help text to explain this subtility or change the UQDPar.py file to mirror the help text?

**Comment by SBriere** [comment]
Indeed, the help text hasn't been updated with those changes.
In fact, the implementation for this API should be  improved as mentionned in Refs #21, to improve APIs handling of multiple parameters at once.
