### ISSUE TITLE
VideoRehabService: Allow camera change and screen sharing start on remote participants

### ISSUE THREAD

**Issue by SBriere** [introlab/opentera#76]
Currently, camera change and screen sharing can only be started locally, for ourselves.
However, it would be interesting to allow a user to change a participant camera remotely (to switch from front or back camera on a mobile device, for example) or to start screen sharing (to stream a software running on that participant's screen).

**Comment by doumdi** [comment]
Screen sharing (remote) is not required for now.

**Comment by SBriere** [comment]
Remote screen sharing is now required for at least one project.
